replicaCount: 1

namespace: dip
moduleName: flow-web

image:
  registry: acr.aishu.cn
  repository: /dip/flow-web
  tag: 3.0.0.5
  pullPolicy: IfNotPresent
  name: flow-web

service:
  ingressclassname: ''
  agentWEB:
    type: ClusterIP
    port: 3045
    nodePort: 3045
    ingress:
      enabled: true
      interface:
        path:
          - /flow-web
  enableDualStack: false
  type: ClusterIP
  ports:
    port1: 3045
    protocol1: TCP
    targetPort1: 3045
    name1: flow-web
  enableSensitiveWordDetection: false

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 11
    memory: 20Gi

probe:
  livenessProbe:
    httpGet:
      path: /probe
      port: 3045
    initialDelaySeconds: 25
    periodSeconds: 50
    timeoutSeconds: 20
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /probe
      port: 3045
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /probe
      port: 3045
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

nodeSelector: {}

depServices:

enableSystemLog: true

rps:
  limit: 100 #每秒最大请求数
