apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flow-automation.fullname" . }}-ca
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "flow-automation.fullname" . }}
{{ include "flow-automation.labels" . | indent 4 }}
data:
    # mongo ca 证书
  mongo.ca.pem:  {{ .Values.depServices.mongodb.sslCAFile | quote }}