{{- $fullName := print (include "vega-metadata.fullname" .) "" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "vega-metadata.labels.backend" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vega-metadata.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vega-metadata.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.config.backend.hostAliases -}}
      hostAliases:
        {{- range .Values.config.backend.hostAliases -}}
        - {{- toYaml . | nindent 10 -}}
        {{ end }}
      {{ end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vega-metadata.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $fullName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.config.backend.health }}
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0
          envFrom:
            - configMapRef:
                name: {{ $fullName }}
          volumeMounts:
            - name: {{ $fullName }}
              mountPath: /metadata-manage/config/application.yml
              readOnly: true
              subPath: application.yml
      volumes:
        - name: {{ $fullName }}
          configMap:
            name: {{ $fullName }}
            items:
              - key: config-yml
                path: application.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
