apiVersion: v1
kind: Service
metadata:
  name: coderunner-private
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: coderunner-private
{{ include "coderunner.labels" . | indent 4 }}
spec:
  {{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: coderunner-port
      protocol: TCP
      name: coderunner-port
  selector:
    app.kubernetes.io/name: {{ include "coderunner.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: dataflowtools-private
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: dataflowtools-private
{{ include "coderunner.labels" . | indent 4 }}
spec:
  {{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.privatePort }}
      targetPort: dft-private
      protocol: TCP
      name: dft-private
  selector:
    app.kubernetes.io/name: {{ include "coderunner.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: dataflowtools-public
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: dataflowtools-public
{{ include "coderunner.labels" . | indent 4 }}
spec:
  {{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.publicPort }}
      targetPort: dft-public
      protocol: TCP
      name: dft-public
  selector:
    app.kubernetes.io/name: {{ include "coderunner.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}