apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moduleName }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    module: {{ .Values.moduleName }}
spec:
  selector:
    module: {{ .Values.moduleName }}
  type: {{ .Values.service.streamDataPipeline.type }}
  ports:
    - name: {{ .Values.moduleName }}
      port: {{ .Values.service.streamDataPipeline.port }}
      protocol: TCP
      targetPort: pipeline
      {{- if eq .Values.service.streamDataPipeline.type "NodePort" }}
      nodePort: {{ .Values.service.streamDataPipeline.nodePort }}
      {{- end }}
