redis:
  connectInfo:
    username: "root"
    password: "yourpassword"
    host: ""
    port: 26379
    masterHost: ""
    masterPort: 26379
    slaveHost: ""
    slavePort: 26379
    sentinelHost: "proton-redis-proton-redis-sentinel.resource.svc.cluster.local"
    sentinelPort: 26379
    sentinelUsername: "root"
    sentinelPassword: "yourpassword"
    masterGroupName: "mymaster"
