project:
  language: zh-CN
  host: "0.0.0.0"
  port: 30779
  logger_level: 1
  name:
  pod_id: "POD_ID"
  machine_id: ""
  debug: false
concept_search_config:
  concept_recall_size: 100
  knn_k: 300
deploy_agent:
  concept_intention_analysis_agent_key: "01K5FS890WD4V7M27GAXER8JKB" # 概念意图分析智能体Key
  concept_retrieval_strategist_agent_key: "01K5G6JFAVJF94C40K90YMPJN9" # 概念召回策略智能体Key
  metric_dynamic_params_generator_key: "01KCG0MEPBNHHZHCSM5NTXRFSG" # Metric 动态参数生成智能体Key
  operator_dynamic_params_generator_key: "01KCJJ7PAK3ATSC02F48QJXFH8" # Operator 动态参数生成智能体Key
oauth: # 对应hydra服务
  public_host: "hydra-public.anyshare"
  public_port: 4444
  public_protocol: "http"
  admin_host: "hydra-admin.anyshare"
  admin_port: 4445
  admin_protocol: "http"
  admin_prefix: "/admin"
user_management:
  private_host: "user-management-private.anyshare"
  private_port: 30980
  private_protocol: "http"
agent_app:
  private_protocol: "http"
  private_host: "agent-app.anyshare"
  private_port: 30777
ontology_manager:
  private_protocol: "http"
  private_host: "ontology-manager-svc.anyshare"
  private_port: 13014
ontology_query:
  private_protocol: "http"
  private_host: "ontology-query-svc.anyshare"
  private_port: 13018
data_retrieval:
  private_protocol: "http"
  private_host: "data-retrieval.anyshare"
  private_port: 9100
operator_integration:
  private_protocol: "http"
  private_host: "agent-operator-integration.anyshare"
  private_port: 9000
redis:
  connectType: "sentinel"
  enableSSL: false
  secretName: ""
  caName: ""
  certName: ""
  keyName: ""
  poolSize: 10
