apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-delete-job
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
  annotations:
    # 注意，如果没有下面的这个注释的话，当前的这个Job就会被当成release的一部分
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}
        version: {{ .Chart.Version }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-delete-job
          image: {{ template "manage-web.image" . }}
          command:
            - "sh"
            - "-c"
            - >
              curl -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/vega &&
              curl -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/data-connect &&
              curl -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/view &&
              curl -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/model-managenent &&
              curl -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/metric-model &&
              curl -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/ontology &&
              curl -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/ontology-manage &&
