apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moduleName }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    module: {{ .Values.moduleName }}
spec:
{{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
{{- end }}
  selector:
    module: {{ .Values.moduleName }}
  type: {{ .Values.service.manageWeb.type }}
  clusterIP: None
  ports:
    - name: {{ .Values.moduleName }}
      port: {{ .Values.service.manageWeb.port }}
      protocol: TCP
      targetPort: manage-web