apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
stringData:
  # 配置文件路径/sysvol/conf/agent-operator-integration-secret.yaml
  agent-operator-integration-secret.yaml: |
    db:
      host: {{ .Values.depServices.rds.host | quote }}
      port: {{ .Values.depServices.rds.port }}
      user_name: {{.Values.depServices.rds.user | quote }}
      password: {{.Values.depServices.rds.password | quote }}
      db_name: {{ .Values.depServices.rds.database | quote }}
      charset: {{ .Values.depServices.rds.dbCharset | quote }}
    redis:
      connectInfo:
        username: {{.Values.depServices.redis.connectInfo.username | quote }}
        password: {{.Values.depServices.redis.connectInfo.password | quote }}
        host: {{.Values.depServices.redis.connectInfo.host | quote }}
        port: {{.Values.depServices.redis.connectInfo.port }}
        masterHost: {{.Values.depServices.redis.connectInfo.masterHost | quote }}
        masterPort: {{.Values.depServices.redis.connectInfo.masterPort }}
        slaveHost: {{.Values.depServices.redis.connectInfo.slaveHost | quote }}
        slavePort: {{.Values.depServices.redis.connectInfo.slavePort }}
        sentinelHost: {{.Values.depServices.redis.connectInfo.sentinelHost | quote }}
        sentinelPort: {{.Values.depServices.redis.connectInfo.sentinelPort }}
        sentinelUsername: {{.Values.depServices.redis.connectInfo.sentinelUsername | quote }}
        sentinelPassword: {{.Values.depServices.redis.connectInfo.sentinelPassword | quote }}
        masterGroupName: {{.Values.depServices.redis.connectInfo.masterGroupName | quote }}
