{{- $fullNameBackend := print (include "vega-metadata.fullname" .) "" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vega-metadata.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "vega-metadata.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ index .Values.depServices "class-443" "ingressClass" }}
  rules:
    - http:
        paths:
        - path: /api/metadata-manage
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullNameBackend }}
              port: 
                name: http