server:
  runMode: release
  httpPort: 13014
  language: zh-CN
  readTimeOut: 120
  writeTimeOut: 600
  maxConcurrentTasks: 4
  viewDataLimit: 1000
  defaultSmallModelName: embedding
  defaultSmallModelEnabled: true
  jobMaxRetryTimes: 3
  reloadJobEnabled: false
log:
  logLevel: debug
  developMode: false
  maxAge: 100
  maxBackups: 20
  maxSize: 100
observability:
  logEnabled: false
  traceEnabled: false
  metricEnabled: false
  logExporter: console
  traceProvider: http
  metricProvider: http
  logLoadInternal: 1
  logLoadMaxLog: 10
  traceMaxQueueSize: 50000
  metricIntervalSecond: 60
  httpLogFeedIngesterUrl: http://feed-ingester-service:13031/api/feed_ingester/v1/jobs/dip-o11y-log/events
  httpTraceFeedIngesterUrl: http://feed-ingester-service:13031/api/feed_ingester/v1/jobs/dip-o11y-trace/events
  httpMetricFeedIngesterUrl: http://feed-ingester-service:13031/api/feed_ingester/v1/jobs/dip-o11y-metric/events
  grpcTraceFeedIngesterUrl: feed-ingester-service:30013
  grpcTraceJobId: dip-o11y-trace-grpc
depServices:
  class-443:
    ingressClass: class-443
  rds:
    host: localhost
    port: 30006
    user: test
    password: testpwd
    type: MariaDB
  opensearch:
    host: localhost
    port: 30000
    protocol: http
    user: test
    password: testpwd
  mq:
    auth:
      mechanism: PLAIN
      password: testpwd
      username: test
    mqHost: kafka-headless.resource.svc.cluster.local.
    mqPort: 9097
    mqType: kafka
    protocol: sasl_plaintext
    tenant: default
  authorization-private:
    host: localhost
    port: 30920
    protocol: http
  user-management: 
    host: localhost
    port:  30981
    protocol: http
  hydra-admin:
    host: localhost
    port: 4445
    protocol: http
  mf-model-manager:
    host: localhost
    port: 9898
    protocol: http
  mf-model-api:
    host: localhost
    port: 9899
    protocol: http
  data-model:
    host: localhost
    port: 13020
    protocol: http
  uniquery:
    host: localhost
    port: 13011
    protocol: http
  business-system:
    host: localhost
    port: 18080
    protocol: http
